### ISSUE TITLE
CLI seemingly hangs after updating to 2.0

### ISSUE THREAD

**Issue by zachsa** [guybedford/chomp#106]
Hi,

Previously I had chomp 0.1.15 installed (`chomp --version`). After running `npm install -g chomp` to update chomp, the CLI just hangs. Eventually it started working again - I guess this is because it's building binaries?

If the CLI get give a 'please wait' message until it's ready that would be more user friendly (I thought I had found a bug).

Otherwise, thank you for the wonderful software! :)

**Comment by guybedford** [comment]
It's downloading the binary in the background because Chomp on npm uses https://www.npmjs.com/package/bin-wrapper.

This wrapper doesn't currently provide functionality to detect the download, if we move to another approach we could add a message though.

> Otherwise, thank you for the wonderful software! :)

Glad to hear it!
