### ISSUE TITLE
Request for debouncing file changes

### ISSUE THREAD

**Issue by zachsa** [guybedford/chomp#124]
I have the following workflow:

```
I save a file => prettier rewrites the file => then chomp does it's thing
```

But currently the chomp task runs immediately on file save, and then is aborted and restarts on the prettier save. Could `chomp` support debouncing?

In this case the chomp task would run x ms after the last time a watched file is saved (say 100ms). This is similar to the nodemon `--delay` option

**Comment by guybedford** [comment]
We could certainly add an `watch-invalidation: 'delay'` field to a task. Perhaps supporting `none` would allow tasks which don't change when used in watch mode as well.

**Comment by guybedford** [comment]
I believe this was implemented, but please reopen if I'm wrong.
