### ISSUE TITLE
Multiple target builds

### ISSUE THREAD

**Issue by guybedford** [guybedford/chomp#13]
If there are multiple ways to build the same target, rather than throwing we can instead handle validation as any of the build paths being valid.

Then when invalidated, the closest build path (the one with the least work) can be used.

This effectively enables a sort of mini conditional build approach without needing a predicate system just yet.

**Comment by guybedford** [comment]
This is pretty complex, closing for now.

**Comment by canadaduane** [comment]
Would it make sense to have a simple "sort order" for now? You could add an optional "order" or "precedence" field with a numeric value. Highest number wins?

**Comment by guybedford** [comment]
Good point, I've posted a separate issue at https://github.com/guybedford/chomp/issues/28 to make sure we clarify this.
