### ISSUE TITLE
--watch should pick up new files

### ISSUE THREAD

**Issue by zachsa** [guybedford/chomp#138]
Using `chomp --watch`, and a task with `deps = [src/**/*.js]`, if I add a new file `src/something/else.js`, chomp currently doesn't pick this up.

**Comment by guybedford** [comment]
This is a duplicate of your previously created issue at https://github.com/guybedford/chomp/issues/126. I appreciate your enthusiasm for this use case, but let's continue tracking this there.

**Comment by zachsa** [comment]
Thanks - I didn't know it was the same issue
