### ISSUE TITLE
Feature request - support glob deps in interpolates when dep will always be a single file

### ISSUE THREAD

**Issue by zachsa** [guybedford/chomp#139]
Currently I have a task for generating import maps that is run on changes to an html file:

```
[[task]]
name = 'jspm:client'
targets = ['.cache/#.html']
deps = [
    'client/html/#.html',
    '.cache'
]
invalidation = 'always'
run = "node jspm-client.js"
```

I would like to be able to change the location of the html files, so that the deps becomes `client/pages/**/#.html`. I think this is generally useful (although since this job is always re-run for all html files I can just remove the interpolation from this and discover HTML files manually)

In this case the output of .cache is a rollup build that contains an unknown number of chunks

**Comment by guybedford** [comment]
What is the reason you cannot just use `client/html/##.html` as the dep and `.cache/##.html` as the target?

**Comment by zachsa** [comment]
ah. i didn't know that was possible

**Comment by guybedford** [comment]
Yes that is what the double interpolate form is for.

**Comment by zachsa** [comment]
This doesn't work as I want to normalize the output directory to be flat.

**Comment by guybedford** [comment]
Right, but flattening is by definition a many to one mapping, which cannot be supported in interpolation as interpolation must be fully reversible in its analysis.

**Comment by zachsa** [comment]
I see - thank you
