### ISSUE TITLE
Chomp self-build error

### ISSUE THREAD

**Issue by guybedford** [guybedford/chomp#148]
With the latest Chomp (0.2.8), `chomp` in Chomp itself is not working:

```
$ chomp
● src/main.rs [cached]
🞂 :build
    Finished dev [unoptimized + debuginfo] target(s) in 0.28s
√ :build [407.8866ms]
🞂 :test
√ :test:clean [48.2877ms]
Error: File C:/Users/guybe/Projects/chomp-rs/test/output/lib/dep.js not found
```

This is likely something to do with not using the right cwd.

//cc @Aslemammad (note apart from that, the new version seems to work well in most projects I've tested so far!)

**Comment by Aslemammad** [comment]
I'll try working on this soon! Just have many serious problems here with the internet.
