### ISSUE TITLE
Suggestion: use 'chomp' as CLI

### ISSUE THREAD

**Issue by canadaduane** [guybedford/chomp#18]
I like brevity, but I also appreciate being able to learn what's happening when seeing others' code or commands for the first time. I think using the full name "chomp" will lead to better outcomes wrt sharing and teaching.

FWIW I see "chp" and want to pronounce it "chip".

edit to add: I considered aliasing `chomp` to `chp` so I could see the full name and find familiarity with the project & name, but then thought that was silly and made this suggestion instead :)

**Comment by guybedford** [comment]
Good point - we could just go for chomp, my concern was just it can be tricky to type sometimes...

**Comment by canadaduane** [comment]
Yeah, I thought that may be the case. I agree the "m" in there is not optimal. "chop" is easy to type, but perhaps even more misleading from a pedagogical standpoint? :/

**Comment by guybedford** [comment]
Yeah I think you're right, chomp isn't _that bad_ to type I suppose. Will push that up in the next commit.
