### ISSUE TITLE
Server says "Hello World" independent of code

### ISSUE THREAD

**Issue by canadaduane** [guybedford/chomp#26]
I wrote a little svelte app that said "hello world" (lower case) and was totally confused when the app showed "Hello World" (capitalized).

I believe there is an internal "Hello World" web page being sent by the chomp server?

Could it instead show instructions about how to create a public 'index.html' page somewhere in the project directory, or explain how to configure chomp to find it?

**Comment by guybedford** [comment]
I'm so sorry that is an hilariously confusing bug. I've fixed up the server to serve index.html by default, with proper contextual not found. We can possibly add a default landing page with nice instructions etc later on.
