### ISSUE TITLE
Global template options

### ISSUE THREAD

**Issue by guybedford** [guybedford/chomp#27]
Global environment passing to templates was recently added. This works as a sort of global template configuration space.

But for a feature like `autoInstall` which is an option on every template, it could be useful to explicitly treat this as global template configuration instead of an environment variable.

The suggestion would be to not pass `env` into templates, but instead pass `globalTemplateConfig`, where this is configured like:

```toml
[global_config]
  pkgManager = 'yarn'
  autoInstall = true
```

**Comment by canadaduane** [comment]
Perhaps `[defaults]` would make sense here? Implying that if not set at the
top-level, the individual task args can override.

**Comment by guybedford** [comment]
One issue with that is that template arguments are like function arguments - specific to each template, so I was kind of thinking more of a global config dictionary that plugins could hook into. Of course the problem of name confusions still arises, but is perhaps more clear in this framing.

**Comment by guybedford** [comment]
This was implemented in https://github.com/guybedford/chomp/pull/31 as being a double map for default options by template name.

So:

```toml
[default-template-opts.npm]
  auto-install = true
```
