### ISSUE TITLE
Configure HTTP server root

### ISSUE THREAD

**Issue by canadaduane** [guybedford/chomp#30]
Currently, `chomp -s` serves files from the project root. However, I would like to be able to specify `./lib` as the HTTP server root so that "https://localhost:8080/" maps to "[PROJECT_ROOT]/lib/".

**Comment by guybedford** [comment]
Added in https://github.com/guybedford/chomp/commit/5b9ec643bec09adb198a3d15f0d695b8c0289fa9, with a new:

```toml
[server]
  port = 8080
  root = "lib"
```

configuration as well as a `--server-root=lib` command-line flag.
